"""empty message

Revision ID: 17dcfdb79c03
Revises: c9a8bc6b8467
Create Date: 2021-03-16 23:08:34.124830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dcfdb79c03'
down_revision = 'c9a8bc6b8467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('date', 'end')
    op.drop_column('date', 'start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('start', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('date', sa.Column('end', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('date', 'date')
    # ### end Alembic commands ###
