"""empty message

Revision ID: 2ab03b96f7ff
Revises: 18d93901cc42
Create Date: 2021-03-16 23:21:33.524250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ab03b96f7ff'
down_revision = '18d93901cc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('leave_id', sa.Integer(), nullable=False))
    op.drop_column('notification', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('notification', 'leave_id')
    # ### end Alembic commands ###
